## About Dataset

**Content:**

This data set contains details of a bank's customers and the target variable is a binary variable reflecting the fact whether the customer left the bank (closed his account) or he continues to be a customer.

**Acknowledgements:**

Big thanks to https://www.superdatascience.com/pages/deep-learning

Banner Photo by Sharon McCutcheon on Unsplas

# Artificial Neural Network

In [ ]:
# Mount to the colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 1. Libraries

In [ ]:
# Import the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow  as tf
import sklearn

In [ ]:
tf.__version__

'2.15.0'

# 2. import Dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ANN/Churn_Modelling.csv")
# All the columns except last one
x = df.iloc[:, 3:-1].values
# Except all the columns only last column needed
y = df.iloc[:, -1].values

In [ ]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


# 3. Data Pre-processing

1. Encoding Categorical data

Label encoding "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [ ]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

OneHotEnoding for "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

2. Spliting the dataset for train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, train_size=0.7, random_state=0)

3. Feature scaling


In [ ]:
# Feature Scaling for neural network
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# 4. Building ANN

In [ ]:
# Initialize the ANN
ann = tf.keras.models.Sequential()

# Adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# 5. Training ANN

1. Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam',
            loss = 'binary_crossentropy',
            metrics = ['accuracy'])

Training the ANN on training set

In [ ]:
# training the data
history = ann.fit(
    x_train,y_train,
    batch_size=32,
    epochs=100,
    verbose=True
)

Epoch 1/100
219/219 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7160
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4874 - accuracy: 0.7980
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.8001
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.8030
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8050
Epoch 6/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8156
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8266
Epoch 8/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3791 - accuracy: 0.8349
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8417
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3640 - accura

### Let's make predictions and also experiments on the dataset

Geography: France

CreditScore: 600

Gender: Male

Age: 40 yrs

Tenure: 3 yrs

Balanace: $60000

number of products: 2

Has Credit card: Yes or No?

Customer Active: Yes or No?

Estimated Salary: $50000

Exited: yes or no?

In [ ]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
# Lets make predictions and any predictions method must be 2D array
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
# Fit transform used to get means values and comparing with threhold value 0.5

1/1 [==============================] - 0s 30ms/step
[[False]]


**Important note-1:**  Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects 2D arrays as the format of its input and putting our values into a double pair of square brackets makes the input excatly a 2D array.

**Important note-2:** "france" column was not a input as a string in the last column but as "1, 0, 0" in the first three columns. Thats because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of the features X, "france" was encoded as "1, 0, 0" and be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

## Predicting the Test set results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

94/94 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2247  132]
 [ 299  322]]


0.8563333333333333